### ISSUE TITLE
One-click install on Linux does not remove characters that are not allowed on Windows

### ISSUE THREAD

**Issue by Dr-Turtle** [affederaffe/BeatSaberModManager#3]
There are characters that can be used as Linux directory/file names but not Windows (The list ModAssistant uses is in this [file](https://github.com/Assistant/ModAssistant/blob/master/ModAssistant/Classes/Utils.cs)), when a path with illegal characters is referenced (e.g. `Directory.GetFiles("Z:\path\with\illegal*name\")`), an exception is thrown (`System.IO.IOException: Error 123`), this causes SongCore to stop loading beatmaps once an illegal path is encountered.

I have not tested what happens on Windows, but I assume there is reason to also check for this on Windows given that ModAssistant does

A temporary fix for anyone seeing this before it's patched is to disable one-click installs in BeatSaberModManager and use [this](https://github.com/Supreeeme/beatsaber-oneclick-linux) instead

**Comment by affederaffe** [comment]
Hi, good catch!
I used System.IO.Path.GetInvalidPathChars() before for this use case, but it seems to be platform specific so it doesm't contain invalid NTFS characters on Linux. Mono still checks for them though since it runs through Wine, causing the Exception. It'll be fixed with the next update.

**Comment by Dr-Turtle** [comment]
thanks for the quick fix, loving this mod manager btw, much more convenient than the other options on Linux

**Comment by Skunkynator** [comment]
I just recently came across this very same issue with the playlist install feature.
This took me quite a long time to figure out why my maps did not all load, assuming it was an issue with SongCore rather then the way i installed some playlists.
A little hotfix build, or disclaimer about this in the readme would be lovely, and probably save alot of time and headache for users of this otherwise amazing mod manager.

**Comment by Dr-Turtle** [comment]
This issue was also very frustrating for me, I went as far to modify SongCore's source code to add extra debug messages before I figured this out, I think even just this bug would justify creating a new release given how difficult it is for a user to determine the cause.

**Comment by affederaffe** [comment]
The plan was to release an update alongside Avalonia 11, which is expected to release in [2023 Q1](https://github.com/AvaloniaUI/Avalonia/discussions/9648#discussioncomment-4334225). Do you think it's fast enough or is it so urgent to justify an early release?

**Comment by Dr-Turtle** [comment]
Is there anything preventing you from creating a new release now? Again, it was very difficult to find the cause of this, so I imagine i'm not the only one who became frustrated when many songs stop loading (to be clear, it's not just songs with illegal characters, it's every song after the first one that fails)

I'm not asking for my sake - I'm using a source build of a more recent version because installing a PKGBUILD is easier than manually installing

**Comment by Skunkynator** [comment]
I would personally also say this would be quite high priority since i also went as far as to modify song core to get debug messages, figuring out what even was wrong, and even then i didn't consider the illegal characters for like 2-3h.

Its especially frustrating since all songs after that one fails arent loaded, and in game song/playlist downloaders also crap out alot. basically this bug just occuring once on a users machine makes modded beatsaber quite a bad experience as a whole afterwards imho.
